#pragma once
enum Species {NONE, ELEPHANT, GIRAFFE, LION, TIGER, ORANGUTAN, CHIMPANZEE, KOMODO, BEAR, WHALE, DOLPHIN, CLOWNFISH, BLUETANG, PIRANHA, PUFFFISH, EAGLE, CENDRAWASIH, OWL, BAT, MACAU, COCKATOO, FROG, ALLIGATOR, HIPPOPOTAMUS, TURTLE};
enum Sex {MALE, FEMALE};
enum Color {RED, ORANGE, YELLOW, GREEN, BLUE, MAGENTA, CYAN, WHITE};
enum Habitat {LANDHABITAT, WATERHABITAT, AIRHABITAT, AMPHIBIAN};
